POST http://localhost:3001/api/persons 
Content-Type: application/json 

{
  "name":"Liisa Marttinen","number":"040-243563"
}
###
DELETE http://localhost:3001/api/persons/4
###
PUT http://localhost:3001/api/persons/689d40f998da0498f271842d
Content-Type: application/json

{
  "name":"puka",
  "number":"19"
}